version: "2.1"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "localhost/test", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 1)';"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  dbdata:
    driver: local